AWSTemplateFormatVersion: 2010-09-09
Transform: 'AWS::Serverless-2016-10-31'

Description: S3 Deployment Layer
Resources:
  S3DeploymentLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      CompatibleRuntimes:
        - python3.6
        - python3.7
      Description: S3 Deployment Layer
      LicenseInfo: MIT
      ContentUri: ../build
      RetentionPolicy: Retain

  DeploymentPermission:
    Type: AWS::Lambda::LayerVersionPermission
    Properties:
      Action: lambda:GetLayerVersion
      LayerVersionArn: !Ref S3DeploymentLayer
      Principal: '*'

Outputs:
  Arn: 
    Value: !Ref S3DeploymentLayer

Metadata:
  AWS::ServerlessRepo::Application:
    Name: deploy-to-s3 
    Description: >
      Deploy and publish Frontend SPA apps, UI components, static websites and MicroFrontends to S3 
      and Serverless Application Repository using this Lambda Layer component
    Author: Aleksandar Simovic
    SpdxLicenseId: MIT 
    LicenseUrl: ../LICENSE.txt
    ReadmeUrl: README-SAR.md 
    Labels: ['deploy', 's3', 'lambda', 'layer', 'frontend']
    HomePageUrl: https://serverless.pub/deploy-frontend-to-s3-and-sar/
    SemanticVersion: 2.4.0
    SourceCodeUrl: https://github.com/serverlesspub/cloudformation-deploy-to-s3
